<?php

/**
 * @file
 * Contains worldtime.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

define('WORLDTIME_MAX_LOCATIONS', 5);
define('WORLDTIME_DEFAULT_TIMEFORMAT', 'HH:mm');
define('WORLDTIME_DEFAULT_SKIN', 1);

/**
 * Implements hook_help().
 */
function worldtime_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the worldtime module.
    case 'help.page.worldtime':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Adds a block with World Clock Time widget') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function worldtime_theme() {
  return array(
    'wtcwidget' => array(
      'variables' => array(
        'items' => NULL,
      ),
      'file' => 'worldtime.theme.inc',
    ),
  );
}

/**
 * Get timezone offset.
 *
 * @param string $timezone
 *
 * @return int
 *   Timezone offset in hours.
 * @throws \Exception
 */
function worldtime_get_timezone_offset($timezone) {
  $dtz = new \DateTimeZone($timezone);
  $dt = new \DateTime('now', $dtz);
  $offset = $dtz->getOffset($dt);
  return $offset / 3600;
}
