<?php

/**
 * @file
 * Contains worldtime.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function worldtime_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the worldtime module.
    case 'help.page.worldtime':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Adds a block with World Clock Time widget') . '</p>';
      return $output;

    default:
  }
}
